openshift/pagerduty-operator

pkg/controller/clusterdeployment/clusterdeployment_controller.go

Per SDA-852 we want to watch on the label `api.openshift.com/managed` instead of just `managed`

Move from the managed label to api.openshift.com/managed

---

cmd/manager/main.go

We want to listen across the entire cluster and not just in 1 namespace

Listen on all namespaces

---

pkg/controller/clusterdeployment/clusterdeployment_created.go
pkg/controller/clusterdeployment/clusterdeployment_deleted.go
pkg/controller/syncset/syncset_deleted.go
pkg/pagerduty/service.go

Make the PagerDuty Service name unique across all hive instances.
On SyncSet delete try and get the service first, if that fails create a
new PagerDuty Service.
We need to make sure that the PagerDuty Service names are unique across all hive instances. Also on SyncSet delete we should try running a GetService first, if that fails run a CreateService. This  is useful in the initial migration to unique service names
/cc @jharrington22 
/cc @jewzaam

Migrate to unique PagerDuty service names

---

pkg/controller/clusterdeployment/clusterdeployment_created.go
pkg/controller/syncset/syncset_deleted.go

During migration to the new pagerduty service name I hit a few edge cases. This should solve them.
Edge Cases Fixed:
- If the syncset is deleted and a new operator is rolled out, it does not know how to handle reconciling them since they have the finalizer, I changed how I set the finalizer, and then I run a GetService instead of just create, so it will check to see if any existing PD Services exist and reuse that before creating a new service
- Fixed the case of the CD name being different from the clusterid in the syncset. It seems that the cluster deployment does not need to share the same name as the cluster id, so I am passing in the correct name for the ClusterID to the syncset.
/cc @jewzaam 
/cc @lisa

Fix a couple edge cases

---

manifests/02-role.yaml

We were missing the delete permissions on syncsets.

Allow deletion of syncsets

---

pkg/controller/syncset/syncset_controller.go

We need to check the length of request.Name before we splice it to prevent out of bounds.

Add a check around request.name length before splicing

---

cmd/manager/main.go
manifests/06-prometheus-k8s-role.yaml
manifests/07-prometheus-k8s-rolebinding.yaml
pkg/metrics/metrics.go
pkg/metrics/service.go

This PR ensures that when the operator is deployed, all the proper objects are placed so prometheus can scrape the custom metrics.
-The operator creates a pagerduty-operator service to expose the metrics over on deploy
-The operator creates a pagerduty-operator servicemonitor to tell prometheus how to digest the metrics
-Removes the operator-sdk metrics service for now
-Includes a prometheus-k8s role for the pagerduty-operator namespace that has permissions to get, list and watch services, pods and endpoints.
-Includes a prometheus-k8s rolebinding to allow the prometheus-k8s serviceaccount from the openshift-monitoring namespace to use the aformentioned role.
When the operator and the role/rolebindings are deployed, the pagerduty-operator namespace must be given the following label to get …

Deploy needed objects for prometheus metrics when the operator comes up

---

config/config.go
pkg/controller/clusterdeployment/clusterdeployment_controller.go
pkg/controller/clusterdeployment/clusterdeployment_created.go

We the change of the finalizer name this PR will remove the old name if it exists then returns, will trigger a requeue since the CD changed

Remove legacy finalizers if they exist

---

cmd/manager/main.go
manifests/02-role.yaml
pkg/metrics/service.go

This PR updates the local metrics package to the latest method. It also replaces the creation of a ServiceMonitor with a Route to enable external scraping. 
For reference, the metrics pkg code already exists in the aws-account-operator: https://github.com/openshift/aws-account-operator/blob/master/cmd/manager/main.go

Remove ServiceMonitor in favor of Route for external scraping

---

config/config.go
pkg/pagerduty/service.go

PagerDuty API has the ability to map incident severity to urgency. By
default PagerDuty treats all incidents (even low severity ones) as high
urgency incidents and thus will page, even for the most minor warnings.
This behaviour isn't desired (See SREP-1352). This change will have new
PagerDuty services (eg new clusters) created with a `severity_based`
Incident Urgency Rule to instruct PagerDuty to defer to the incident's
severity to inform urgency.
Signed-off-by: Lisa Seelye <lseelye@redhat.com>

SREP-1352: Specify an IncidentUrgencyRule for new PD Services

---

pkg/localmetrics/localmetrics.go

https://jira.coreos.com/browse/SREP-1941
Unauthenticated API call should be removed from metrics.

Remove un-authenticated PD API call

---

config/config.go
pkg/controller/clusterdeployment/clusterdeployment_controller.go
pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
pkg/controller/clusterdeployment/clusterdeployment_deleted.go
pkg/controller/syncset/syncset_controller.go

https://jira.coreos.com/browse/SREP-1572
Added SyncSet deletion to handleDelete and reference from a few more places.  It checks the finalizer first and bails if there is no finalizer so should be lightweight.

Remove SyncSet if noalerts label is added

---

pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
pkg/controller/clusterdeployment/clusterdeployment_deleted.go

Can't do anything if the config isn't there, it's not a recoverable state.
https://jira.coreos.com/browse/SREP-2250

Ignore missing config on delete

---

hack/app_sre_build_deploy.sh

This is defaulting to the current env's USER which causes image push to fail.
Force it to be "app-sre" if nothing else is set.

Set IMAGE_REPOSITORY

---

standard.mk

Appears I didn't update this correctly originally so it was trying to find a repo that doesn't exist.

Fix the repo name used for the operator bundle

---

hack/app_sre_pr_check.sh

We haven't (and dont' in master yet) have any yaml to validate so never caught this.  With upcoming work to introduce configuration to the operator the PR check is failing because of this.

Fix yaml validation in PR check

---

hack/app_sre_pr_check.sh
hack/validate_yaml.py

- `hack/validate_yaml.py` was a no-op when run under py3 because `yaml.safe_load_all()` produces a generator, and doesn't actually parse the YAML until you iterate on it. Fix.
- Previously `app_sre_pr_check.sh` was assembling YAML directories in an
array, but only "looping" over the first one. Now we intelligently look for all YAML files (.yml or
.yaml suffix) under source control in the current repo and run validation on them one by one.

Fix YAML validation

---

README.md
config/config.go
pkg/controller/pagerdutyintegration/pagerdutyintegration_controller_test.go

https://issues.redhat.com/browse/OSD-4059
A future phase will remove the old label.  Tracked as a task in the above story.

Add support for new 'ext' noalerts label.

---

hack/olm-registry/olm-artifacts-template.yaml

They were being treated as strings by `oc process` and they need to be integers.
Ideally PR check would catch this, not sure how to validate the CR w/o a live cluster though so will open separate PR if/when I can for that.

Fix data type for resolveTimeout and acknowledgeTimeout in template

---

.gitignore
cmd/manager/main.go
pkg/controller/pagerdutyintegration/pagerdutyintegration_controller.go
pkg/localmetrics/localmetrics.go
pkg/localmetrics/localmetrics_test.go
pkg/utils/clientwrapper.go

1) Register 2 new metrics
* `pagerduty_operator_api_request_duration_seconds` timing the kubeclient calls with controller, method, resource and status dimensions 
* `pagerduty_operator_reconcile_duration_seconds` timing the reconcile loop with controller label
2) Instrument the controller-runtime Client to include the metric calculation for each request
3) Standardise the resource from the HTTP request by removing reference to object names to allow proper aggregation 
4) Disable controller-runtime metrics serving as conflicting with the custom-metrics and unused

Implement new metrics for kubeclient and reconcile duration - OSD-4567 + OSD-4569

---

hack/olm-registry/olm-artifacts-template.yaml
pkg/controller/pagerdutyintegration/clusterdeployment_created.go
pkg/controller/pagerdutyintegration/clusterdeployment_deleted.go
pkg/controller/pagerdutyintegration/pagerdutyintegration_controller.go
pkg/controller/pagerdutyintegration/pagerdutyintegration_controller_test.go
pkg/localmetrics/localmetrics.go

It should be specified in the PDI CR.

Don't use old hardcoded PD API key secret

---

hack/olm-registry/olm-artifacts-template.yaml

https://issues.redhat.com/browse/OSD-4817
So we can specify an optional array of legal entity ID's to skip creating PD services for.

Add SKIPPED_LEGALENTITY_IDS array in template

---

build/Dockerfile.catalog_registry

_(bug/feature/cleanup/docs/design/test/chore/refactor..)_
Bug
Openshift-registry introduced a breaking change in 4.6 in their docker image, locking img tag in 4.5
OSD-5077

OSD-5077 Lock registry image in 4.5

---

hack/olm-registry/olm-artifacts-template.yaml

Fix the following error:
```
"request":"pagerduty-operator/osd-silent","error":"\"in\" is not a valid pod selector operator"
```

Use correct capitalization for selector operator

---

hack/olm-registry/olm-artifacts-template.yaml

- `ESCALATION_POLICY_SILENT` wasn't being properly processed by the template
- Standardize on double curly brackets
- Set default value of `'["None"]'` for `SILENT_ALERT_LEGALENTITY_IDS`

Fix template variables

---

hack/olm-registry/olm-artifacts-template.yaml

Apparently when the template processes through CI, it only likes single curly brackets when it is part of a string

Change silent service prefix to single curly brackets

---

hack/olm-registry/olm-artifacts-template.yaml

https://issues.redhat.com/browse/OSD-5375
Note this is ahead of having the label set at all but will position us to use it immediately after available: https://issues.redhat.com/browse/SDA-3021

Update PDI to not alert for 'nightly' channel-group clusters

---

pkg/controller/pagerdutyintegration/pagerdutyintegration_controller.go
pkg/controller/pagerdutyintegration/pagerdutyintegration_controller_test.go
pkg/localmetrics/localmetrics.go
pkg/localmetrics/localmetrics_test.go
pkg/pagerduty/service.go

1) Adding a custom HTTPClient in order to measure API Calls duration and push to prometheus
2) Updating the `resourceFrom` method to manage pagerduty API calls

Implement new metrics for PD API calls

---

functions.mk
standard.mk

The image used for yq was change to be the golang version which has a completely different syntax to the original python version. The entry point for the container is also not correct hence needing the extra `yq`. 
The path to discover what version of the operator promoted to production has changed in app-interface, this has been updated.

Update yq syntax and fix saas file location

---

README.md
config/config.go
hack/olm-registry/olm-artifacts-template.yaml
pkg/controller/pagerdutyintegration/clusterdeployment_created.go
pkg/controller/pagerdutyintegration/clusterdeployment_deleted.go
pkg/controller/pagerdutyintegration/pagerdutyintegration_controller.go
pkg/controller/pagerdutyintegration/pagerdutyintegration_controller_test.go
pkg/utils/utils.go

https://issues.redhat.com/browse/OSD-5594
Unit tests were reworked to cover many more permitations.
Noalerts was removed as part of test rework / simplification.  Therefore this incorporates https://github.com/openshift/pagerduty-operator/pull/124 which will be closed.

Fix to delete PD service for CD that no longer matches PDI

---

README.md

This referred to a clusterdeployment YAML manifest that doesn't exist.
Reword to explain grabbing one from a real hive.

README: reword fake ClusterDeployment section

---

pkg/controller/pagerdutyintegration/clusterdeployment_created.go
pkg/controller/pagerdutyintegration/clusterdeployment_deleted.go

Refactor
This PR changes the logic of the `pagerduty-operator` to perform a `Patch()` of the `clusterdeployment` CR when adding or removing finalizers, rather than an `Update()`, in order to eliminate the possibility that the `Update()` call will drop data from the CR.
[OSD-6070](https://issues.redhat.com/browse/OSD-6070)
I've tested this with a local deployment of `pagerduty-operator` and verified that finalizers are still created and removed as expected. I have also verified that - if the Hive `clusterdeployment` CRD introduces a new field and sets that value in a `clusterdeployment` CR - the currently running operator does not remove that new field when it performs the `Patch()`, as per the goals of [OSD-6070](https://issues.redhat.com/browse/OSD-6070).
Related PRs:
- …

OSD-6070 Patch clusterdeployment instead of update

---

hack/olm-registry/olm-artifacts-template.yaml

This PR adds a PagerDutyInegration CR that will select all managed clusters that have a specific organization ID and route them to a new scale test PD escalation policy.
The organization ID will be a specific org that we use for scale tests its added via parameter in the OC template in this [MR](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/15310)

Add scale test PagerdutyIntegration

---

build/Dockerfile.catalog_registry

This addresses a vulnerability with regards to the 4.x origin-operator-registry image
https://issues.redhat.com/browse/OSD-6834

Use The origin-operator-registry latest Base Image

---

hack/olm-registry/olm-artifacts-template.yaml

This reverts commit 55ce32bafdb01c9017f730ca165f8689e3c65a2c.
For hive operators, we need a fix in sretoolbox before this will work.

Revert "OSD-6853: CatalogSource by digest"

---

hack/olm-registry/olm-artifacts-template.yaml

Reverts openshift/pagerduty-operator#146
The blocking [issue](https://github.com/app-sre/sretoolbox/pull/34) has been [fixed](https://github.com/app-sre/sretoolbox/pull/35) and promoted through [qontract-reconcile](https://github.com/app-sre/qontract-reconcile/pull/1515) and [app-interface](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/18070/diffs). The saas file change has been [unreverted](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/18105).

Revert "Revert "OSD-6853: CatalogSource by digest""

---

pkg/controller/pagerdutyintegration/clusterdeployment_deleted.go
pkg/pagerduty/service.go
pkg/pagerduty/service_test.go

When deleting a cluster, we delete incidents before deleting the underlying service in PD and as this is an asynchronous event on PD side, we are waiting to confirm incident closure.
However, in case the incidents don't get closed within the defined maxWait, we continue with the service deletion which lead to orphaned incidents we cannot delete. 
Instead, we should raise an error in case the incidents didn't get closed in time : 
- in case the incidents got eventually deleted, the cleanup will proceed properly with next reconcile
- in case the event got dropped, the operator will send again the closure event which should go through

OSD-8440 - Fix for orphaned incidents in PagerDuty

---

hack/olm-registry/olm-artifacts-template.yaml

PD operator is unable to create configmap for this service due to RFC violation using `_` 
The configmap name is bult from ServicePrefix
```
/home/dofinn/go/src/github.com/openshift/pagerduty-operator/config/config.go
31:     ConfigMapSuffix          string = "-pd-config"
/home/dofinn/go/src/github.com/openshift/pagerduty-operator/pkg/controller/pagerdutyintegration/clusterdeployment_deleted.go
46:             configMapName string = config.Name(pdi.Spec.ServicePrefix, cd.Name, config.ConfigMapSuffix)
/home/dofinn/go/src/github.com/openshift/pagerduty-operator/pkg/controller/pagerdutyintegration/clusterdeployment_hibernated.go
30:             configMapName string = config.Name(pdi.Spec.ServicePrefix, cd.Name, config.ConfigMapSuffix) …
```

OSD-9041 fixes cm name for osd-silent

---

config/config.go
pkg/controller/pagerdutyintegration/clusterdeployment_created.go
pkg/controller/pagerdutyintegration/clusterdeployment_limited_support.go
pkg/controller/pagerdutyintegration/pagerdutyintegration_controller.go
pkg/controller/pagerdutyintegration/pagerdutyintegration_controller_test.go
pkg/kube/configmap.go
pkg/pagerduty/service.go

Resolves: [OSD-10025](https://issues.redhat.com/browse/OSD-10025)
<hr>
- This PR switches the PagerDuty service enabled/disabled based on the `api.openshift.com/limited-support` label in the cluster deployment.
- When `api.openshift.com/limited-support` is set to **true** the cluster related PagerDuty service is disabled and any active alerts are automatically resolved.
- When `api.openshift.com/limited-support` is set to anything else other than true or if the label is deleted the cluster related PagerDuty service is re-enabled and alerting is resumed.

OSD-10025: Disable PagerDuty service when a cluster is in limited support

---

.gitignore
go.mod
go.sum
pkg/pagerduty/service.go
pkg/pagerduty/service_test.go

Refactored `waitForIncidentsToResolve` per [OSD-10751](https://issues.redhat.com/browse/OSD-10751) to add a more verbose error message containing incident IDs.

Increase information in error message when incidents fail to resolve

---

pkg/controller/pagerdutyintegration/clusterdeployment_created.go
pkg/controller/pagerdutyintegration/pagerdutyintegration_controller_test.go
pkg/pagerduty/service.go

After unit tests are in place from #180 and #181 (shouldn't be merged before those two),
Correct a typo and simplify `getConfigMapKey` and `GetSecretKey`

[OSD-10189] Simplify GetSecretKey and getConfigMapKey

---

pkg/pagerduty/service.go
pkg/pagerduty/service_mock.go
pkg/pagerduty/service_test.go

This bug occurs sometimes when a PagerDuty service has more than one integration because `GetIntegrationKey` returns only one integration, while `resolveAlert` (renamed from `resolveIncident`) needs a correct integration key + alert key combination to successfully resolve an alert.
This was not too obvious because the PagerDuty Events V2 API (which `resolveAlert` uses) returns an HTTP 202 (success) regardless if the integration key + alert key combination matches, the API simply acknowledges that the event was received and contains all the necessary arguments. Luckily, alerts themselves indicate the integration that generated them, so the fix wasn't too bad (can isolate onto the second commit for the entire fix). I validated this fix locally by identifying clusters were failing to have …

[OSD-10751] Fix bug where the operator was failing to delete some alerts

---

pkg/controller/pagerdutyintegration/clusterdeployment_created.go
pkg/controller/pagerdutyintegration/clusterdeployment_deleted.go
pkg/controller/pagerdutyintegration/clusterdeployment_hibernated.go
pkg/controller/pagerdutyintegration/clusterdeployment_limited_support.go
pkg/pagerduty/service.go
pkg/pagerduty/service_test.go

Created a new function, `NewData`, to default the "Data" struct to contain PDIEscalationPolicyID by default.
Then, updated `ParseClusterConfig` such that EscalationPolicyID defaults to PDIEscalationPolicyID when missing.

[OSD-10917] Default escalationpolicyid to prevent errors in deletion

---

deploy/operator.yaml
manifests/05-operator.yaml

PDO is currently getting OOMKilled on hivep01ue1. Increasing the memory requests/limits here to mitigate the risk of PDO crashing.

Increase Memory requests/limits to 2G

---

pkg/controller/pagerdutyintegration/clusterdeployment_created.go
pkg/controller/pagerdutyintegration/clusterdeployment_deleted.go
pkg/controller/pagerdutyintegration/clusterdeployment_hibernated.go
pkg/controller/pagerdutyintegration/clusterdeployment_limited_support.go
pkg/pagerduty/service.go
pkg/pagerduty/service_test.go
pkg/utils/utils.go

After pushing in a fix for [OSD-10917](https://issues.redhat.com/browse/OSD-10917), we noticed some issues disabling services in stage. The first thing that came to mind was that during creation/deletion, we are setting an APIKey https://github.com/openshift/pagerduty-operator/blob/68f87792db1dcd3c9e0014793e49ea4211a1c5fd/pkg/controller/pagerdutyintegration/clusterdeployment_created.go#L105 but we weren't during the hibernation/limited_support workflows. The log message was extremely vague because `clusterId` and `baseDomain` never get set in the hibernation/limited_support workflows.
But how did this ever work? It's because the controller already sets up the PagerDuty client with an API key https://github.com/openshift/pagerduty-operator/blob/68f87792db1dcd3c9e0014793e49ea4211a1c5fd/pkg/c …

[OSD-10917] Cleanup Data struct to remove unneeded ApiKey and require ClusterId and BaseDomain

---

pkg/controller/pagerdutyintegration/clusterdeployment_deleted.go
pkg/controller/pagerdutyintegration/pagerdutyintegration_controller.go
pkg/controller/pagerdutyintegration/pagerdutyintegration_controller_test.go
pkg/pagerduty/service.go
pkg/pagerduty/service_test.go
pkg/utils/secrets.go
pkg/utils/secrets_test.go

The main idea is to accumulate errors in a new `type pdiReconcileErrors []error` which implements the builtin error interface, allowing a full reconcile loop to complete before requeuing.
This is important because the operator effectively tries to reconcile all ClusterDeployments each time, attempting delete actions before any creates. This meant that any bugs in PagerDuty service deletion would cause the operator to be unable to attempt to create new PagerDuty services until the service deletion was remediated.
Along the way I found `utils.LoadSecretData` was duplicated by `pagerduty.GetSecretKey`, so I removed GetSecretKey. Likewise, `utils. GetHashOfPullSecret` was unused and so removed.

[OSD-10189] Accumulate errors during the reconcile loop instead of immediately bailing

---

go.mod
go.sum
pkg/controller/pagerdutyintegration/pagerdutyintegration_controller.go
pkg/pagerduty/mock_service.go
pkg/pagerduty/service.go
pkg/pagerduty/service_mock.go

The three commits in this PR are for:
1. Updating go-pagerduty to v1.5.0 to pull in some fixes from https://github.com/PagerDuty/go-pagerduty/pull/384
2. It wasn't enough, so raised https://github.com/PagerDuty/go-pagerduty/issues/438 and added a wrapper function for now to get around the bug we're facing with `UpdateService`
3. At this point a full reconcile loop completed in stage for the first time in a while, with one last failure on saying `Reconcile complete` when there were no errors, so I added a `len(reconcileErrors) > 0` check

OSD-10934 Fix bug preventing successful enabling/disabling of PD services

---

README.md
pkg/controller/pagerdutyintegration/clusterdeployment_created.go
pkg/controller/pagerdutyintegration/pagerdutyintegration_controller_test.go
pkg/pagerduty/service.go
pkg/pagerduty/service_test.go

Relates to: [OSD-12385](https://issues.redhat.com/browse/OSD-12385)
<hr>
- Currently, for existing PagerDuty services, the PD ConfigMaps do not have the `EscalationPolicyID` data field. Only the newly created service ConfigMaps have it.
- This is necessary to detect when there is a change in the PagerDutyIntegration escalation policy, compare it with the existing ConfigMap escalation policy, update the service and reconcile.
- Default to using PagerDutyIntegration CR's `EscalationPolicyID` as the source of truth for PagerDuty Operator escalation policy. This makes the `PDIEscalationPolicyID` field obsolete.
- Check if the ClusterDeployment's ConfigMap has the `ESCALATION_POLICY_ID` key, if not, map it to the PagerDutyIntegration CR `EscalationPolicyID` and update the ConfigMap. This will …

Update ConfigMap EscalationPolicyID data field on reconcile

---

go.mod
go.sum
pkg/pagerduty/mock_service.go
pkg/pagerduty/service.go

`UpdateService()` previously had a bug so that we needed to implement our own workaround, however it has since been fixed in https://github.com/PagerDuty/go-pagerduty/pull/448, so removing our custom wrapper since we no longer need it!

OSD-12437 Use upstream `UpdateService`

---

config/config.go
pkg/controller/pagerdutyintegration/pagerdutyintegration_controller.go
pkg/pagerduty/service.go

Doing a prelim run of the gosec linter found a few issues, this PR addresses those findings and fixes them.
The ones in the config.go file were flagged as possible hard coded passwords, that is a false positive and the test has been disabled for those lines.

[OSD-11466] Addresses findings by the gosec linter

---

api/v1alpha1/pagerdutyintegration_types.go
deploy/crds/pagerduty.openshift.io_pagerdutyintegrations.yaml

currently, the OLM failed to deploy the new version of the operator to cluster
In csv there are errors:
```
Group:    apiextensions.k8s.io
Kind:     CustomResourceDefinition
Message:  CRD installed alongside other CSV(s): pagerduty-operator.v0.1.418-7b8d16f
Name:     pagerdutyintegrations.pagerduty.openshift.io
Status:   PresentNotSatisfied
Version:  v1
```
And in installplan, there are errors:
```
message: 'error validating existing CRs against new CRD''s schema for "pagerdutyintegrations.pagerduty.openshift.io":
error validating custom resource against new schema for PagerDutyIntegration
pagerduty-operator/addon-managed-api-service: [].spec.serviceOrchestration:
Required value'
```
Need to make the new field in CRD optional to pass the check.
cc @NautiluX

make the service orchestration optional

---

controllers/pagerdutyintegration/clusterdeployment_created.go
controllers/pagerdutyintegration/pagerdutyintegration_controller_test.go
controllers/pagerdutyintegration/serviceorchestration_handler.go
pkg/kube/configmap.go
pkg/pagerduty/service.go

Set the `ServiceOrchetrationEnabled`(was `ServiceOrchestrationState`) and `ServiceOrchestrationRuleApplied` separately in the cluster configmap to make sure the reconcile loop could handle them separately.
There was a problem before, that it is possible the `ServiceOrchestrationState` set to `active` when the ServiceOrchestration enabled but the ServiceOrchestration rule was not applied due to it is missing at the beginning. And the reconcile loop will not apply it anymore when the rule added since the value set the `active`. It will also be an issue if we want to update the rule in future.
Separated indicator in configmap could call the `ToggleServiceOrchestration` and `ApplyServiceOrchestrationRule` in parallel. 
Also add the related tests.

set the enable service orchestration and apply orchestration rule as parallel logic

---

hack/olm-registry/olm-artifacts-template.yaml

Adds `SERVICE_ORCHESTRATION_ENABLED` and `SERVICE_ORCHESTRATION_RULE_CONFIGMAP` as template parameters to the OLM Artifacts template.
#209 introduced some additional templating parameters to the olm artifacts template, but did not specify them as explicit parameters in the `parameters` section, meaning that they are not getting values injected as part of the SaaS pipeline.
Refs [OSD-13740](https://issues.redhat.com//browse/OSD-13740)

OSD-13740 Specify missing template parameters

---

hack/olm-registry/olm-artifacts-template.yaml

This "stringifies" the default bool value for the SERVICE_ORCHESTRATION_ENABLED variable as app-interface expects this to be a string.

Update Default OLM Template Value

---

hack/templates/00-osd-serviceorchestration.configmap.yaml.tmpl

- Introduces a new template representing the pagerduty-operator's service orchestration configmap. 
This template will be processed by app-interface to deploy the processed template onto Hive shards so that pagerduty-operator can (when enabled) perform service orchestration enablement on managed PD services.
_Why is this being introduced as a separate template rather than in the OLM template bundle?_
- I don't believe a processed template for this is a valid resource to go in the OLM catalog bundle. Including it as part of the catalog would require promoting a new release of the pagerduty operator every time we want to roll out service orchestration rule updates. Rule updates, especially if we grow them in the future, should stand independent of the operator.
_Why can this not be deployed …

Add service orchestration configmap template

---

controllers/pagerdutyintegration/event_handlers.go
controllers/pagerdutyintegration/pagerdutyintegration_controller_test.go
controllers/pagerdutyintegration/serviceorchestration_handler.go
pkg/kube/configmap.go
pkg/pagerduty/service.go

write the contents of the service orchestration rule to the clusterconfigmap
so that, we can skip the `ApplyServiceOrchestrationRule()` call if it has been applied already.
The logic will be:
- Read the `serviceorchestrationconfigmap` for pagerduty-operator to configure the service orchestration
- Read the `clusterconfigmap` which includes the applied orchestration rule
- Apply if value in `clusterconfigmap` does not match the `serviceorchestrationconfigmap`
- Update the `clusterconfigmap` after apply

write service orchestration rule data to clusterconfigmap directly

---

main.go
pkg/pagerduty/service.go

- Wraps errors stemming from pagerduty-client interactions with more context regarding what action was caused to trigger the error.
- Log timestamps in human-readable form rather than epoch seconds (took inspiration from [this](https://github.com/openshift/cloud-ingress-operator/pull/280) PR)
The errors returned from the pagerduty client library rarely give any context as to what API interaction took place. This makes it confusing or misleading when reviewing PDO logs to understand why an error is occurring. This PR wraps each error with additional context surrounding the call so that when it is passed up the chain there is a clearer picture of why the failure is occurring.
[OSD-14350](https://issues.redhat.com//browse/OSD-14350)

Add more context to errors with pagerduty client interaction

---

controllers/pagerdutyintegration/handleupdate.go
controllers/pagerdutyintegration/pagerdutyintegration_controller.go
controllers/pagerdutyintegration/pagerdutyintegration_controller_test.go

This updates the `handleUpdate()` function (and section of the reconcile loop where it's called) to ensure that existing clusters have alert grouping enabled when configured via a pagerdutyintegration. There are unit tests for the reconcile loop that should confirm this behavior

OSD-16066 Ensure alert grouping gets applied to existing clusters

---

controllers/pagerdutyintegration/handleupdate.go

When nil, it would seg fault.
[OHSS-24073](https://issues.redhat.com//browse/OHSS-24073)

Fix issue where AlertGroupingParameters was nil

---

build/Dockerfile.olm-registry
controllers/pagerdutyintegration/serviceorchestration_handler.go
hack/templates/00-osd-serviceorchestration.configmap.yaml.tmpl
pkg/pagerduty/service_mock.go
pkg/utils/utils.go

This PR is a requirement for https://issues.redhat.com/browse/OSD-17861 - after merging this, we will need to update `app-interface` with the according `rh-infra-service-orchestration.json`
**What?**
This PR enables us to pass a second event orchestration configuration that will be applied to Red Hat infrastructure clusters (currently targets hypershift SC and MC). 
**Why?**
We want to be able to react to infrastructure cluster alerts before other alerts, so that we can fix issues that possibly impact a large number of other clusters quickly. For this, we need to be able to customize infrastructure cluster alerts, which can be done using the following event orchestration configuration applied to only infrastructure clusters:
```
rh-infra-service-orchestration.json: |
{ …
```

feat: allow a separate event orchestration for RH infra clusters

---

pkg/pagerduty/service.go

**Why?**
The current logging for `UpdateService` does not enable us to trace back what updating failed.
**What?**
Add context to failed `UpdateService` calls
Fixes https://issues.redhat.com/browse/OSD-17913

OSD-17913: Update logging for service updates to reflect what is being updated

---

pkg/pagerduty/service.go

When parsing a cluster config for a PagerDuty Data, skip past the alert
grouping parameters. This will cause the Data to keep the alert grouping
parameters from the pagerdutyintegration (set in NewData()), which is
used for the update query to Pager Duty.
The configmap values for alert grouping will be updated after the update
query is successful, and are thus only used to check if an update needs
to be made.

OSD-17911 alert grouping bugfix

---

build/Dockerfile
build/Dockerfile.olm-registry
controllers/pagerdutyintegration/serviceorchestration_handler.go
pkg/pagerduty/service.go

Sometimes, PDO does not correctly apply the service orchestration (filtering out warning alerts) to a service. 
**The issue:** PDO does not query the service orchestration data from PD, instead it caches the "applied" data for every service in a configmap. This cache is inconsistent due to a bug.
**The bug:** the cached data was inconsistent with the actual applied pagerduty data, as we don't properly check if a HTTP request succeeds (documentation of `http.DefaultClient.Do)` :
```
An error is returned if caused by client policy (such as CheckRedirect), or failure to speak HTTP (such as a network connectivity problem). A non-2xx status code doesn't cause an error.
```
We only check if an error occurs, but don't check the returned status code of the http request.
**The fix:** we only …

fix(OSD-15493): service orchestrations not setup correctly for some PD services

---

pkg/pagerduty/service.go

To address an error with a race condition on the limited support status from the perspective of the service. For [OSD-18059](https://issues.redhat.com//browse/OSD-18059)

When disabling a service always resolve with the limited support message

---

hack/olm-registry/olm-artifacts-template.fedramp.yaml
hack/olm-registry/olm-artifacts-template.yaml

We are in the process of removing PagerDuty from FedRAMP.  This is the first of a few PRs that will occur over the next few months.  This phase will remove PD from all non-production clusters while production clusters will remain active with pager duty.  We will target this new template for fedramp.  Once we have fully transitioned from PD/DMS, this template will be removed.

OSD-18468 - template for fedramp removal

---

config/config.go
controllers/pagerdutyintegration/clusterdeployment_limited_support.go

Introduce a new label that will keep pagerduty active if the ClusterDeployment has a support exception label.

Keep PD active if CD has support exception label

---

build/Dockerfile
build/Dockerfile.olm-registry
config/config.go
hack/olm-registry/olm-artifacts-template.yaml

as part of https://issues.redhat.com/browse/SREP-101 ticket where we ensured that the PD Operator configured with olm.skipRange, and UnsafeFailForward.

Updates to prevent stuck subscriptions
