openshift/pagerduty-operator

- config/templates/pagerduty-operator-csv-template.yaml
- hack/app_sre_build_deploy.sh
- hack/app_sre_create_image_catalog.sh
- hack/app_sre_pr_check.sh
- hack/generate-operator-bundle.py
- hack/olm-registry/olm-artifacts-template.yaml
This PR adds the deploy scripts required to deploy via the app-sre pipeline
> Add build scripts for app-sre deploy

- config/config.go
- hack/generate-operator-bundle.py
- manifests/01-namespace.yaml
- manifests/02-role.yaml
- manifests/03-service_account.yaml
- manifests/04-role_binding.yaml
- manifests/05-config.yaml
- manifests/06-operator.yaml
- pkg/pagerduty/service.go
Move to a new namespace and upadte the generate-operator-bundle.py to work with manifests directory.
> Spec change

- hack.sh
- manifests/05-operator.yaml
Moving the image from my personal quay repo to the team repo.
> Update the quay image location

- manifests/05-operator.yaml
This PR updates the operator image to push to the app-sre quay.io repository
> Update operator image location

- Makefile
- build/Dockerfile
The PR updates the makefile to take an argument containing a docker image name
> Update docker image name

- manifests/02-role.yaml
- manifests/04-role_binding.yaml
Add permissions that lets us set finalizers on cluster deployments
> Add clusterdeployments to the role

- pkg/pagerduty/syncset.go
> Change syncset to sync from upsert

- pkg/pagerduty/syncset.go
> Change the namespace in the syncset

- pkg/controller/clusterdeployment/clusterdeployment_created.go
- pkg/controller/clusterdeployment/clusterdeployment_deleted.go
- pkg/controller/syncset/syncset_controller.go
- pkg/controller/syncset/syncset_deleted.go
- pkg/kube/configmap.go
- pkg/kube/syncset.go
- pkg/pagerduty/service.go
Create Integrations for each service created and use the integration key inside the syncset
/cc @lisa 
/cc @jewzaam
> Create Integrations for each new service

- pkg/controller/clusterdeployment/clusterdeployment_created.go
- pkg/controller/clusterdeployment/clusterdeployment_deleted.go
I simplified the deletion to help prevent errors during clean up. Instead of the operator handling deletion of my objects I set their owner to the CD and I am letting k8s handle cleaning them up.
This issue has been created https://github.com/openshift/pagerduty-operator/issues/37 to help with the new system in that we let it fail.
> Simplify delete and let k8s clean up a lot of items on NS delete

- pkg/pagerduty/service.go
Unlike integrations service names have to be unique, so if we have an error creating a service we search the error string and see if one already exists, if it does query pagerduty and get the existing service.
> If a service already exists in pagerduty use the existing service

- hack/app_sre_create_image_catalog.sh
> migrate saas repos to ci-int

- config/config.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/syncset/syncset_controller.go
- pkg/controller/syncset/syncset_controller_test.go
https://jira.coreos.com/browse/SREP-1572
> Add support for a 'noalerts' label

- config/config.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterdeployment/clusterdeployment_deleted.go
- pkg/controller/syncset/syncset_controller.go
- pkg/controller/syncset/syncset_controller_test.go
- pkg/controller/syncset/syncset_deleted.go
- pkg/kube/configmap.go
- pkg/kube/syncset.go
- pkg/pagerduty/service.go
- pkg/utils/utils.go
It won't be recreated by the SyncSet controller.
It will be deleted if noalerts is applied.
Unit tests updated to check these.
Some refactoring.
> Fixed deletion of SyncSet

- config/config.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/clusterdeployment/clusterdeployment_created.go
- pkg/controller/clusterdeployment/clusterdeployment_deleted.go
- pkg/controller/syncset/syncset_controller_test.go
- pkg/controller/syncset/syncset_deleted.go
- pkg/kube/syncset.go
- pkg/pagerduty/service.go
- pkg/utils/utils.go
https://jira.coreos.com/browse/SREP-1830
> Use secretReference in syncset

- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/syncset/syncset_controller_test.go
- pkg/utils/utils.go
https://issues.redhat.com/browse/OSD-2661
> Change "noalerts" label to require "true" value

- README.md
Updating the readme with a few things that I learnt while adding an End to end test for the operator.
> Update Readme for pagerduty operator

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
fix some small issues in the code and add more test coverage for the referenced secret.
> add more unit tests for the referenced secret

- manifests/05-operator.yaml
Current usage on stg and prod
STG:
pagerduty-operator                             pagerduty-operator-687b46cb99-cq7tw              6m           91Mi
PROD:
pagerduty-operator                                pagerduty-operator-5f886655f5-fzn42                6m           65Mi
> add resource requests/limits per OSD-2109

- Makefile
- README.md
- build/Dockerfile
- build/bin/entrypoint
- build/bin/user_setup
- functions.mk
- hack/app_sre_build_deploy.sh
- hack/app_sre_pr_check.sh
- project.mk
- standard.mk
Taking what is the current state of configure-alertmanager-operator with one small tweak in how CONTAINER_ENGINE is set.
Did not carry forward all scripts as this requires job changes and is a much bigger scope.
Driver was I couldn't build this locally for many previously-solved-in-other-repos reasons.
> Update make and build stuff to be more consistent

- hack/olm-registry/olm-artifacts-template.yaml
https://issues.redhat.com/browse/OSD-4579
> Add "osd" PagerDutyIntegration CR to the template

- OWNERS
> Update OWNERS, adding reviewers

- README.md
- Generate a TOC.
- Replace non-rendering angle brackets with curly braces.
- Use a link for an internal reference.
> Aesthetic README updates

- manifests/05-operator.yaml
* align requests and limits
* increase memory limit
> Increase requests and limits

- cmd/manager/main.go
Since #133, the pagerduty-operator has been crash looping with:
```
{"level":"info","ts":1607820868.0212517,"logger":"cmd","msg":"Starting the Cmd."}
panic: close of closed channel
goroutine 910 [running]:
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*specificInformersMap).Start.func1(0xc0005260e0, 0xc00021dda0)
pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/cache/internal/informers_map.go:141 +0x157
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*specificInformersMap).Start(0xc0005260e0, 0xc00021dda0)
pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/cache/internal/informers_map.go:142 +0x35
created by sigs.k8s.io/controller-runtime/pkg/cache/internal.(*InformersMap).Start
pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/cache/internal/deleg_map.go:62 +0x80
```
This is …
> Add localmetrics runner to manager

- functions.mk
See also https://github.com/openshift/osd-metrics-exporter/pull/43
> Pin to yq 3.4.1 tag

- manifests/05-operator.yaml
* Prevent operator from getting OOMKilled
> Increase memory requests & limits

- pkg/controller/pagerdutyintegration/clusterdeployment_created.go
- pkg/controller/pagerdutyintegration/clusterdeployment_hibernated.go
- pkg/controller/pagerdutyintegration/pagerdutyintegration_controller.go
- pkg/controller/pagerdutyintegration/pagerdutyintegration_controller_test.go
- pkg/kube/configmap.go
- pkg/pagerduty/mock/mock_service.go
- pkg/pagerduty/service.go
Jira: https://issues.redhat.com/browse/OSD-6923 
Docs for hibernation: https://github.com/openshift/hive/blob/master/docs/hibernating-clusters.md
- This switches the pd service enabled/disable on powerState state.
- When hibernating any active alerts are cleared.
> Osd 6923 make hibernation aware

- pkg/controller/pagerdutyintegration/clusterdeployment_created.go
- pkg/controller/pagerdutyintegration/pagerdutyintegration_controller_test.go
Checks if the clusterdeployment has the annotation "managed.openshift.com/fake" and skips the creation of PD services if true.
> OSD-7514 Disable Pagerduty for "fake" OSD clusters

- hack/olm-registry/olm-artifacts-template.yaml
- pkg/controller/pagerdutyintegration/pagerdutyintegration_controller.go
for [OSD-9237](https://issues.redhat.com/browse/OSD-9237)
> detect a fedramp environment and prep a variable for use

- pkg/pagerduty/service_test.go
Should not be merged before #180
Added unit tests for:
* GetConfigMapKey
* GetSecretKey
* ParseClusterConfig
* SetClusterConfig
So that future modifications can get quick feedback.
> [OSD-10189] Improving the test coverage in the pagerduty package

- pkg/pagerduty/service.go
In [OSD-12845](https://issues.redhat.com//browse/OSD-12845), we found that PDO was failing to disable a PagerDuty service after the cluster was placed into limited support. This boiled down to an upstream bug when updating a PagerDuty service has time-based Alert Grouping enabled: https://github.com/PagerDuty/go-pagerduty/issues/458 where calls to `UpdateService` result in the following error due to a JSON unmarshalling bug:
```
HTTP response failed with status code 400,
message: Invalid Input Provided (code: 2001): Config is invalid.
```
Since time-based Alert Grouping is something RL/FL's can do at their discretion and it's quite normal for such services to be eventually put into limited support, this is can be considered a bandaid fix that unsets all alert grouping when …
> OSD-12845 Remove any configured alert grouping to workaround upstream bug

- OWNERS
They will no longer be reviewing PRs
> Remove blrm and grdryn

- deploy/operator.yaml
- manifests/05-operator.yaml
Signed-off-by: Ankit Kurmi <akurmi@redhat.com>
Added missing probes in the CSV deployments. 
Ref: https://github.com/openshift/pagerduty-operator/blob/master/main.go#L74
> feat: Adding probes to csv deployments

- designs/alert_grouping.md
This is a simple proposal for [OSD-16062](https://issues.redhat.com//browse/OSD-16062)
> add a design doc for configuring time-based alert grouping

- hack/olm-registry/olm-artifacts-template.yaml
this allows app-interface to control the alert grouping parameters
> OSD-16066 add parameters for alert grouping to the OLM template

- hack/olm-registry/olm-artifacts-template.yaml
change 0 to "0" to get a json unmarshaling error
> type change

- README.md
- build/Dockerfile.olm-registry
- deploy-extras/pagerduty_v1alpha1_pagerdutyintegration_cr.yaml
**What?**
Maintenance on README and other resources.
**Why?**
Some things weren't fully up to date anymore and caused difficulties while setting up the project for development and testing.
> Update development documentation and resources

- pkg/pagerduty/service.go
- pkg/pagerduty/service_test.go
Adds an additional summary message for resolving alerts due to limited support
for [OSD-18059](https://issues.redhat.com//browse/OSD-18059)
> Add variable resolve message for limited support

- OWNERS
I haven't been involved in this operator for a while, I need to get out of the way :)
> Remove user `jewzaam` from approvers and maintainers
